///************************************************
/// Generated by: DucVT
/// Date: 26/11/2014 12:29:08
/// Goal: Create Form for RPT_NHAN_SU_PERFECT
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;
using IP.Core.IPSystemAdmin;
using IP.Core.IPExcelReport;
using BKI_HRM.US;
using BKI_HRM.DS;
using BKI_HRM.DS.CDBNames;

using C1.Win.C1FlexGrid;

namespace BKI_HRM
{



	public class f306_RPT_NHAN_SU_PERFECT : System.Windows.Forms.Form
	{
		internal System.Windows.Forms.ImageList ImageList;
        internal System.Windows.Forms.Panel m_pnl_out_place_dm;
		internal SIS.Controls.Button.SiSButton m_cmd_delete;
		internal SIS.Controls.Button.SiSButton m_cmd_update;
		internal SIS.Controls.Button.SiSButton m_cmd_insert;
        internal SIS.Controls.Button.SiSButton m_cmd_exit;
        private Panel panel1;
        private Label label1;
        private DateTimePicker m_dat_thoi_diem;
        private C1FlexGrid m_fg;
        internal SIS.Controls.Button.SiSButton m_cmd_xuat_excel;
        private BackgroundWorker backgroundWorker1;
		private System.ComponentModel.IContainer components;

		public f306_RPT_NHAN_SU_PERFECT()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f306_RPT_NHAN_SU_PERFECT));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_xuat_excel = new SIS.Controls.Button.SiSButton();
            this.m_cmd_insert = new SIS.Controls.Button.SiSButton();
            this.m_cmd_update = new SIS.Controls.Button.SiSButton();
            this.m_cmd_delete = new SIS.Controls.Button.SiSButton();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.m_dat_thoi_diem = new System.Windows.Forms.DateTimePicker();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.backgroundWorker1 = new System.ComponentModel.BackgroundWorker();
            this.m_pnl_out_place_dm.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_xuat_excel);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_insert);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_update);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_delete);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 471);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(920, 36);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_xuat_excel
            // 
            this.m_cmd_xuat_excel.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_xuat_excel.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_xuat_excel.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_xuat_excel.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_xuat_excel.Font = new System.Drawing.Font("Arial", 9.75F, System.Drawing.FontStyle.Bold);
            this.m_cmd_xuat_excel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_xuat_excel.ImageIndex = 19;
            this.m_cmd_xuat_excel.ImageList = this.ImageList;
            this.m_cmd_xuat_excel.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_xuat_excel.Name = "m_cmd_xuat_excel";
            this.m_cmd_xuat_excel.Size = new System.Drawing.Size(118, 28);
            this.m_cmd_xuat_excel.TabIndex = 15;
            this.m_cmd_xuat_excel.Text = "Xuất Excel";
            this.m_cmd_xuat_excel.Click += new System.EventHandler(this.m_cmd_xuat_excel_Click);
            // 
            // m_cmd_insert
            // 
            this.m_cmd_insert.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_insert.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_insert.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_insert.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_insert.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_insert.ImageIndex = 2;
            this.m_cmd_insert.ImageList = this.ImageList;
            this.m_cmd_insert.Location = new System.Drawing.Point(564, 4);
            this.m_cmd_insert.Name = "m_cmd_insert";
            this.m_cmd_insert.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_insert.TabIndex = 12;
            this.m_cmd_insert.Text = "&Thêm";
            // 
            // m_cmd_update
            // 
            this.m_cmd_update.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_update.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_update.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_update.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_update.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_update.ImageIndex = 3;
            this.m_cmd_update.ImageList = this.ImageList;
            this.m_cmd_update.Location = new System.Drawing.Point(652, 4);
            this.m_cmd_update.Name = "m_cmd_update";
            this.m_cmd_update.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_update.TabIndex = 13;
            this.m_cmd_update.Text = "&Sửa";
            // 
            // m_cmd_delete
            // 
            this.m_cmd_delete.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_delete.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_delete.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_delete.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_delete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_delete.ImageIndex = 4;
            this.m_cmd_delete.ImageList = this.ImageList;
            this.m_cmd_delete.Location = new System.Drawing.Point(740, 4);
            this.m_cmd_delete.Name = "m_cmd_delete";
            this.m_cmd_delete.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_delete.TabIndex = 14;
            this.m_cmd_delete.Text = "&Xoá";
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(828, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_exit.TabIndex = 11;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.m_dat_thoi_diem);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(920, 76);
            this.panel1.TabIndex = 21;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(339, 32);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(54, 13);
            this.label1.TabIndex = 1;
            this.label1.Text = "Thời điểm";
            // 
            // m_dat_thoi_diem
            // 
            this.m_dat_thoi_diem.CustomFormat = "dd/MM/yyyy";
            this.m_dat_thoi_diem.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_dat_thoi_diem.Location = new System.Drawing.Point(399, 26);
            this.m_dat_thoi_diem.Name = "m_dat_thoi_diem";
            this.m_dat_thoi_diem.Size = new System.Drawing.Size(132, 20);
            this.m_dat_thoi_diem.TabIndex = 0;
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_fg.Location = new System.Drawing.Point(0, 76);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(920, 395);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 22;
            // 
            // backgroundWorker1
            // 
            this.backgroundWorker1.WorkerReportsProgress = true;
            this.backgroundWorker1.DoWork += new System.ComponentModel.DoWorkEventHandler(this.backgroundWorker1_DoWork);
            this.backgroundWorker1.ProgressChanged += new System.ComponentModel.ProgressChangedEventHandler(this.backgroundWorker1_ProgressChanged);
            this.backgroundWorker1.RunWorkerCompleted += new System.ComponentModel.RunWorkerCompletedEventHandler(this.backgroundWorker1_RunWorkerCompleted);
            // 
            // f306_RPT_NHAN_SU_PERFECT
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(920, 507);
            this.Controls.Add(this.m_fg);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "f306_RPT_NHAN_SU_PERFECT";
            this.Text = "F306 - Báo cáo nhân sự phần mềm Perfect";
            this.Load += new System.EventHandler(this.f306_RPT_NHAN_SU_PERFECT_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.ResumeLayout(false);

		}
		#endregion

		#region Public Interface
		public void display(){			
			this.ShowDialog();
		}
		#endregion

		#region Data Structure
		private enum e_col_Number{
			SO_THE_BHYT = 27
,LUONG = 29
,LUONG_DONG_BHXH = 30
,MA_SO_THUE = 24
,NGAY_KET_THUC_HOP_DONG = 36
,HO_DEM = 2
,CHI_NHANH_NGANHANG = 21
,EMAIL_CA_NHAN = 17
,GIOI_TINH = 7
,SO_TAI_KHOAN = 20
,TON_GIAO = 39
,NOI_DAO_TAO = 44
,NOI_SINH = 6
,NGAY_CAP_SO_BHXH = 26
,TIN_HOC = 42
,TRINH_DO = 40
,SKYPE = 45
,NOI_CAP_CMND = 15
,DT_NHA = 17
,DI_DONG = 8
,QUOC_TICH = 37
,NGAY_CAP_CMND = 14
,MA_HOP_DONG = 33
,NGAY_SINH = 5
,CHUYEN_NGANH = 43
,HO_KHAU = 9
,YAHOO = 46
,CHO_O = 10
,NGAY_KY_HOP_DONG = 34
,FACEBOOK = 47
,NGAY_BAT_DAU_HOP_DONG = 35
,NGAY_CO_HIEU_LUC = 31
,GHI_CHU = 50
,MA_CHAM_CONG = 28
,TINH_TRANG_SUC_KHOE = 19
,SO_SO_BHXH = 25
,NGOAI_NGU = 41
,NGAY_HET_HIEU_LUC = 30
,MA_NV = 1
,CMND = 13
,TEN = 3
,MA_CV = 11
,NGAY_BAT_DAU = 12
,DAN_TOC = 38
,DON_VI=4
,TINH_TRANG_HON_NHAN = 18
,CHI_NHANH_NGAN_HANG = 22
,TINH_THANH_PHO = 23
,TRANG_THAI_LAM_VIEC = 48
,NGAY_NGHI_VIEC = 49
,CAP = 51
,BAC = 52
    ,BO_PHAN = 53
        ,	DU_AN = 54
            ,	TY_LE_THAM_GIA = 55
                ,	CHINH_THUC = 56
                    ,	TRANG_THAI_PHU = 57

		}			
		#endregion

		#region Members
        AlertForm alert;
		ITransferDataRow m_obj_trans;		
		DS_RPT_NHAN_SU_PERFECT m_ds = new DS_RPT_NHAN_SU_PERFECT();
		US_RPT_NHAN_SU_PERFECT m_us = new US_RPT_NHAN_SU_PERFECT();
		#endregion

		#region Private Methods
		private void format_controls(){
			CControlFormat.setFormStyle(this, new CAppContext_201());
			CControlFormat.setC1FlexFormat(m_fg);
			CGridUtils.AddSave_Excel_Handlers(m_fg);
            			CGridUtils.AddSearch_Handlers(m_fg);
			set_define_events();
			this.KeyPreview = true;		
		}
		private void set_initial_form_load(){						
			m_obj_trans = get_trans_object(m_fg);
            m_cmd_xuat_excel.Visible = true;
            m_cmd_xuat_excel.Enabled = true;
			load_data_2_grid();		
		}	
		private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
			Hashtable v_htb = new Hashtable();
			v_htb.Add(RPT_NHAN_SU_PERFECT.SO_THE_BHYT, e_col_Number.SO_THE_BHYT);
			v_htb.Add(RPT_NHAN_SU_PERFECT.LUONG, e_col_Number.LUONG);
			v_htb.Add(RPT_NHAN_SU_PERFECT.LUONG_DONG_BHXH, e_col_Number.LUONG_DONG_BHXH);
			v_htb.Add(RPT_NHAN_SU_PERFECT.MA_SO_THUE, e_col_Number.MA_SO_THUE);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGAY_KET_THUC_HOP_DONG, e_col_Number.NGAY_KET_THUC_HOP_DONG);
			v_htb.Add(RPT_NHAN_SU_PERFECT.HO_DEM, e_col_Number.HO_DEM);
			v_htb.Add(RPT_NHAN_SU_PERFECT.CHI_NHANH_NGANHANG, e_col_Number.CHI_NHANH_NGANHANG);
			v_htb.Add(RPT_NHAN_SU_PERFECT.EMAIL_CA_NHAN, e_col_Number.EMAIL_CA_NHAN);
			v_htb.Add(RPT_NHAN_SU_PERFECT.GIOI_TINH, e_col_Number.GIOI_TINH);
			v_htb.Add(RPT_NHAN_SU_PERFECT.SO_TAI_KHOAN, e_col_Number.SO_TAI_KHOAN);
			v_htb.Add(RPT_NHAN_SU_PERFECT.TON_GIAO, e_col_Number.TON_GIAO);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NOI_DAO_TAO, e_col_Number.NOI_DAO_TAO);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NOI_SINH, e_col_Number.NOI_SINH);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGAY_CAP_SO_BHXH, e_col_Number.NGAY_CAP_SO_BHXH);
			v_htb.Add(RPT_NHAN_SU_PERFECT.TIN_HOC, e_col_Number.TIN_HOC);
			v_htb.Add(RPT_NHAN_SU_PERFECT.TRINH_DO, e_col_Number.TRINH_DO);
			v_htb.Add(RPT_NHAN_SU_PERFECT.SKYPE, e_col_Number.SKYPE);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NOI_CAP_CMND, e_col_Number.NOI_CAP_CMND);
			v_htb.Add(RPT_NHAN_SU_PERFECT.DT_NHA, e_col_Number.DT_NHA);
			v_htb.Add(RPT_NHAN_SU_PERFECT.DI_DONG, e_col_Number.DI_DONG);
			v_htb.Add(RPT_NHAN_SU_PERFECT.QUOC_TICH, e_col_Number.QUOC_TICH);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGAY_CAP_CMND, e_col_Number.NGAY_CAP_CMND);
			v_htb.Add(RPT_NHAN_SU_PERFECT.MA_HOP_DONG, e_col_Number.MA_HOP_DONG);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGAY_SINH, e_col_Number.NGAY_SINH);
			v_htb.Add(RPT_NHAN_SU_PERFECT.CHUYEN_NGANH, e_col_Number.CHUYEN_NGANH);
			v_htb.Add(RPT_NHAN_SU_PERFECT.HO_KHAU, e_col_Number.HO_KHAU);
			v_htb.Add(RPT_NHAN_SU_PERFECT.YAHOO, e_col_Number.YAHOO);
			v_htb.Add(RPT_NHAN_SU_PERFECT.CHO_O, e_col_Number.CHO_O);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGAY_KY_HOP_DONG, e_col_Number.NGAY_KY_HOP_DONG);
			v_htb.Add(RPT_NHAN_SU_PERFECT.FACEBOOK, e_col_Number.FACEBOOK);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGAY_BAT_DAU_HOP_DONG, e_col_Number.NGAY_BAT_DAU_HOP_DONG);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGAY_CO_HIEU_LUC, e_col_Number.NGAY_CO_HIEU_LUC);
			v_htb.Add(RPT_NHAN_SU_PERFECT.GHI_CHU, e_col_Number.GHI_CHU);
			v_htb.Add(RPT_NHAN_SU_PERFECT.MA_CHAM_CONG, e_col_Number.MA_CHAM_CONG);
			v_htb.Add(RPT_NHAN_SU_PERFECT.TINH_TRANG_SUC_KHOE, e_col_Number.TINH_TRANG_SUC_KHOE);
			v_htb.Add(RPT_NHAN_SU_PERFECT.SO_SO_BHXH, e_col_Number.SO_SO_BHXH);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGOAI_NGU, e_col_Number.NGOAI_NGU);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGAY_HET_HIEU_LUC, e_col_Number.NGAY_HET_HIEU_LUC);
			v_htb.Add(RPT_NHAN_SU_PERFECT.MA_NV, e_col_Number.MA_NV);
			v_htb.Add(RPT_NHAN_SU_PERFECT.CMND, e_col_Number.CMND);
			v_htb.Add(RPT_NHAN_SU_PERFECT.TEN, e_col_Number.TEN);
			v_htb.Add(RPT_NHAN_SU_PERFECT.MA_CV, e_col_Number.MA_CV);
			v_htb.Add(RPT_NHAN_SU_PERFECT.NGAY_BAT_DAU, e_col_Number.NGAY_BAT_DAU);
			v_htb.Add(RPT_NHAN_SU_PERFECT.DAN_TOC, e_col_Number.DAN_TOC);
            v_htb.Add(RPT_NHAN_SU_PERFECT.DON_VI, e_col_Number.DON_VI);
            v_htb.Add(RPT_NHAN_SU_PERFECT.TRANG_THAI_LAM_VIEC, e_col_Number.TRANG_THAI_LAM_VIEC);
            v_htb.Add(RPT_NHAN_SU_PERFECT.CAP, e_col_Number.CAP);
            v_htb.Add(RPT_NHAN_SU_PERFECT.BAC, e_col_Number.BAC);
            v_htb.Add(RPT_NHAN_SU_PERFECT.BO_PHAN, e_col_Number.BO_PHAN);
            v_htb.Add(RPT_NHAN_SU_PERFECT.TY_LE_THAM_GIA, e_col_Number.TY_LE_THAM_GIA);
			ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds.RPT_NHAN_SU_PERFECT.NewRow());
			return v_obj_trans;			
		}
		private void load_data_2_grid(){						
			m_ds = new DS_RPT_NHAN_SU_PERFECT();			
			m_us.FillDataset(m_ds, CAppContext_201.getCurrentIDPhapnhan(), m_dat_thoi_diem.Value.Date);
			m_fg.Redraw = false;
			CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);
			m_fg.Redraw = true;
		}
		private void grid2us_object(US_RPT_NHAN_SU_PERFECT i_us
			, int i_grid_row) {
			DataRow v_dr;
			v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
			i_us.DataRow2Me(v_dr);
		}

	
		private void us_object2grid(US_RPT_NHAN_SU_PERFECT i_us
			, int i_grid_row) {
			DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			i_us.Me2DataRow(v_dr);
			m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
		}


		private void insert_rpt_nhan_su_perfect(){			
		//	f306_RPT_NHAN_SU_PERFECT_DE v_fDE = new  f306_RPT_NHAN_SU_PERFECT_DE();								
		//	v_fDE.display();
			load_data_2_grid();
		}

		private void update_rpt_nhan_su_perfect(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;			
			grid2us_object(m_us, m_fg.Row);
		//	f306_RPT_NHAN_SU_PERFECT_DE v_fDE = new f306_RPT_NHAN_SU_PERFECT_DE();
		//	v_fDE.display(m_us);
			load_data_2_grid();
		}
				
		private void delete_rpt_nhan_su_perfect(){
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted)  return;
			US_RPT_NHAN_SU_PERFECT v_us = new US_RPT_NHAN_SU_PERFECT();
			grid2us_object(v_us, m_fg.Row);
			try {			
				v_us.BeginTransaction();    											
				v_us.Delete();                      								
				v_us.CommitTransaction();
				m_fg.Rows.Remove(m_fg.Row);				
			}
			catch (Exception v_e) {
				v_us.Rollback();
				CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
					new CDBClientDBExceptionInterpret());
				v_objErrHandler.showErrorMessage();
			}
		}

		private void view_rpt_nhan_su_perfect(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			grid2us_object(m_us, m_fg.Row);
		//	f306_RPT_NHAN_SU_PERFECT_DE v_fDE = new f306_RPT_NHAN_SU_PERFECT_DE();			
		//	v_fDE.display(m_us);
		}
        private void xuat_excel()
        {
            if (backgroundWorker1.IsBusy != true)
            {
                // create a new instance of the alert form
                alert = new AlertForm();
                // event handler for the Cancel button in AlertForm
                //alert.Canceled += new EventHandler<EventArgs>(buttonCancel_Click);
                alert.Show();
                alert.TopMost = true;
                // Start the asynchronous operation.
                backgroundWorker1.RunWorkerAsync();
            }
        }
		private void set_define_events(){
			m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
			m_cmd_insert.Click += new EventHandler(m_cmd_insert_Click);
			m_cmd_update.Click += new EventHandler(m_cmd_update_Click);
			m_cmd_delete.Click += new EventHandler(m_cmd_delete_Click);
            m_dat_thoi_diem.ValueChanged += new EventHandler(m_dat_thoi_diem_ValueChanged);
		}

        
		#endregion

//
		//
		//		EVENT HANLDERS
		//
		//
		private void f306_RPT_NHAN_SU_PERFECT_Load(object sender, System.EventArgs e) {
			try{
				set_initial_form_load();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		
		}

        private void m_dat_thoi_diem_ValueChanged(object sender, EventArgs e)
        {
            try
            {
                load_data_2_grid();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

		private void m_cmd_exit_Click(object sender, EventArgs e) {
			try{
				this.Close();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_insert_Click(object sender, EventArgs e) {
			try{
				insert_rpt_nhan_su_perfect();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_update_Click(object sender, EventArgs e) {
			try{
				update_rpt_nhan_su_perfect();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_delete_Click(object sender, EventArgs e) {
			try{
				delete_rpt_nhan_su_perfect();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_view_Click(object sender, EventArgs e) {
			try{
				view_rpt_nhan_su_perfect();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

        private void m_cmd_xuat_excel_Click(object sender, EventArgs e)
        {
            try
            {
                xuat_excel();
            }
            catch (Exception v_e)
            {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }
        private void backgroundWorker1_DoWork(object sender, DoWorkEventArgs e)
        {
            BackgroundWorker worker = sender as BackgroundWorker;

            for (int i = 1; i <= 1; i++)
            {
                if (worker.CancellationPending == true)
                {
                    e.Cancel = true;
                    break;
                }
                else
                {
                    // Perform a time consuming operation and report progress.
                    worker.ReportProgress(i * 10);
                    //System.Threading.Thread.Sleep(500);
                }
            }
        }

        private void backgroundWorker1_ProgressChanged(object sender, ProgressChangedEventArgs e)
        {
            if (!backgroundWorker1.CancellationPending)
            {
                alert.Message = "In progress, please wait... " + e.ProgressPercentage.ToString() + "%";
                alert.ProgressValue = e.ProgressPercentage;
            }
            var v_start_row = 2;
            var v_start_col = 1;
            var v_obj_excel_rpt = new CExcelReport("Employee.xls", v_start_row, v_start_col);
            //v_obj_excel_rpt.AddFindAndReplaceItem("<ngay_thang>", string.Format("{0}/{1}/{2}", DateTime.Now.Day, DateTime.Now.Month, DateTime.Now.Year));
            v_obj_excel_rpt.FindAndReplace(false);
            v_obj_excel_rpt.Export2ExcelWithoutFixedRows(m_fg, 1, m_fg.Cols.Count - 1, true);
        }

        private void backgroundWorker1_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e)
        {
            alert.Close();
        }

	}
}

