//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_LOGIN_WEB
    {
        public decimal ID { get; set; }
        public string USER_LOGIN { get; set; }
        public System.DateTime DATETIME_LOGIN { get; set; }
        public string STATUS_LOGIN { get; set; }
    }
}
