//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HT_USER
    {
        public System.Guid ID { get; set; }
        public string BHYT { get; set; }
        public string CMND { get; set; }
        public string MSBN { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public bool IS_ACTIVE { get; set; }
        public System.Guid ID_USER_GROUP { get; set; }
        public string USER_GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.Guid> ID_HT_CONTROLLER { get; set; }
        public string CONTROLLER_NAME { get; set; }
        public string ACTIVITY_NAME { get; set; }
        public Nullable<decimal> VI_TRI { get; set; }
        public bool TRANG_THAI_YN { get; set; }
        public Nullable<System.Guid> ID_CHUC_NANG_CHA { get; set; }
        public bool HIEN_THI_YN { get; set; }
        public string ICON_CLASS { get; set; }
        public string CHUC_NANG_CON { get; set; }
        public string CHUC_NANG_CHA { get; set; }
    }
}
